// Generated by scripts/sync-experts.py. Do not edit manually.
export const EXPERT_CATALOG_REVISION = "97296662e6fb8e9c836e18580e3708a2463807bb";
export const BUILTIN_EXPERT_CATALOG = [
  {
    "id": "technology",
    "name": "科技类翻译大师",
    "description": "翻译代码、API 文档和技术教程，保留命令、路径、标识符与专业术语。",
    "version": "1.0.0"
  },
  {
    "id": "medical",
    "name": "医学翻译大师",
    "description": "翻译医学、临床和生命科学内容，准确处理诊断、药物、剂量、单位与医学编码。",
    "version": "1.0.0"
  },
  {
    "id": "design",
    "name": "设计师",
    "description": "翻译设计、艺术和创意内容，保留风格、材质、技法、作品名称与审美意图。",
    "version": "1.0.0"
  },
  {
    "id": "legal",
    "name": "法律翻译专家",
    "description": "翻译合同、法规和法律条款，明确保留定义、义务、条件、例外与管辖关系。",
    "version": "1.0.0"
  },
  {
    "id": "financial",
    "name": "金融翻译专家",
    "description": "翻译财报、投资和市场内容，准确保留金额、币种、比例、日期、风险与金融术语。",
    "version": "1.0.0"
  },
  {
    "id": "news",
    "name": "新闻翻译专家",
    "description": "翻译新闻和时事报道，保持事实、时间线、消息来源、引语与中性新闻语气。",
    "version": "1.0.0"
  },
  {
    "id": "paper",
    "name": "论文翻译专家",
    "description": "翻译论文和学术材料，保留研究方法、证据、引用、统计数据与论证结构。",
    "version": "1.0.0"
  },
  {
    "id": "fiction",
    "name": "小说翻译专家",
    "description": "翻译小说和叙事文本，保留人物声音、对白、视角、气氛、节奏与文学意象。",
    "version": "1.0.0"
  },
  {
    "id": "plain-english",
    "name": "通俗英语专家",
    "description": "把复杂或官样的表达翻得更清楚直接，但不删减条件、限制、警告和关键信息。",
    "version": "1.0.0"
  },
  {
    "id": "bilingual-mix",
    "name": "双语混合专家",
    "description": "翻译时保留重要原文术语，并在必要处附上简洁对应表达，适合术语学习和对照阅读。",
    "version": "1.0.0"
  },
  {
    "id": "word-by-word",
    "name": "逐句对照专家",
    "description": "尽量保持原文句子和段落对应关系，适合逐句对照、学习和检查译文完整性。",
    "version": "1.0.0"
  },
  {
    "id": "paraphrase",
    "name": "意译润色专家",
    "description": "在不改变事实和意图的前提下进行自然意译与润色，适合需要更流畅的成稿。",
    "version": "1.0.0"
  },
  {
    "id": "github",
    "name": "GitHub 专家",
    "description": "翻译 GitHub Issue、PR 和 README，保留命令、路径、Markdown、提交与协作术语。",
    "version": "1.0.0"
  },
  {
    "id": "reddit",
    "name": "Reddit 专家",
    "description": "翻译 Reddit 等社区讨论，保留口语、幽默、俚语、社区梗和发言者语气。",
    "version": "1.0.0"
  },
  {
    "id": "twitter",
    "name": "社交媒体专家",
    "description": "翻译短帖和社交媒体内容，保留简短节奏、话题标签、提及、链接与传播语气。",
    "version": "1.0.0"
  },
  {
    "id": "game",
    "name": "游戏翻译专家",
    "description": "翻译游戏文本和玩家指南，统一处理角色、道具、技能、界面、数值与玩家口吻。",
    "version": "1.0.0"
  },
  {
    "id": "music",
    "name": "音乐翻译专家",
    "description": "翻译歌词和音乐内容，保留歌词结构、节奏、意象、音乐术语、歌手与作品名称。",
    "version": "1.0.0"
  },
  {
    "id": "ecommerce",
    "name": "电商翻译专家",
    "description": "翻译商品页和电商营销内容，兼顾卖点、规格、价格、行动号召与自然的销售语气。",
    "version": "1.0.0"
  },
  {
    "id": "web3",
    "name": "Web3 翻译专家",
    "description": "翻译区块链、加密资产和去中心化应用内容，保留协议、代币、钱包与技术术语。",
    "version": "1.0.0"
  },
  {
    "id": "classical-to-modern",
    "name": "古文今译专家",
    "description": "把文言文、古籍和史料译成现代汉语，解释古代表达、典故、人物和历史语境。",
    "version": "1.0.0"
  },
  {
    "id": "chess",
    "name": "国际象棋专家",
    "description": "翻译棋谱、开局和对局分析，保留着法记谱、变例、棋手名称与战术关系。",
    "version": "1.0.0"
  },
  {
    "id": "ebook",
    "name": "电子书专家",
    "description": "翻译长篇电子书，持续统一人名、术语、叙事语气和段落结构，适合分章阅读。",
    "version": "1.0.0"
  },
  {
    "id": "ao3",
    "name": "同人文学专家",
    "description": "翻译 AO3 和同人作品，保留圈内术语、人物关系、标签、警告与角色语气。",
    "version": "1.0.0"
  },
  {
    "id": "steam",
    "name": "Steam 社区专家",
    "description": "翻译 Steam 评论和玩家社区内容，保留游戏术语、口语、评价态度与社区表达。",
    "version": "1.0.0"
  },
  {
    "id": "subliminal-lingo",
    "name": "潜意识语言专家",
    "description": "翻译需要保留潜台词、暗示和语言模式的内容，尽量不抹平隐含语气与表达层次。",
    "version": "1.0.0"
  },
  {
    "id": "database",
    "name": "数据库专家",
    "description": "翻译数据库和 SQL 内容，保留表结构、字段、查询、约束、执行计划与数据库术语。",
    "version": "1.0.0"
  },
  {
    "id": "paragraph-summarizer",
    "name": "段落摘要",
    "description": "翻译段落摘要和提要，保留中心论点、关键证据、专名、数字与可执行结论。",
    "version": "1.0.0"
  },
  {
    "id": "vocabulary-assistant",
    "name": "词汇助手",
    "description": "用于词汇学习和术语理解，突出词义、上下文、搭配与必要的原文表达。",
    "version": "1.0.0"
  },
  {
    "id": "wyw",
    "name": "文言雅译专家",
    "description": "把现代或外语内容译得更古雅凝练，保留意象、典故、情绪、节奏和含蓄的文学表达。",
    "version": "1.0.0"
  }
] as const;
